# Generated by Django 3.0.1 on 2020-01-08 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200107_1930'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReadNum',
        ),
    ]
